Controllers/CalendarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tennis.Models;

namespace Tennis.Controllers
{
    public class CalendarController : Controller
    {
        private UsersContext _db;
        public CalendarController(UsersContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<OkObjectResult> GetEvents()
        {

            var events = await _db.Tournaments.ToListAsync();
            return Ok(events);
        }

    }
   
}

Views/Calendar/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="calender"></div>


<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>
        $(document).ready(function () {
            var events = [];
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetEvents","Calendar")',
                success: function (data) {
                    console.log(data);
                    $.each(data, function (i, v) {
                        events.push({
                            title: v.name,
                            category: v.category,
                            date: moment(v.date),
                            categoryLeagueTournament: v.categoryLeagueTournament,
                            type: v.type,
                            userCount: v.userCount,
                            status: v.status,
                            url: '@Url.Action("DetailsTournament", "Tournament")' + "/" + v.id
                        });
                    })
                    GenerateCalender(events);
                },
                error: function (error) {
                    alert('failed');
                }
            })

            function GenerateCalender(events) {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    contentHeight: 500,
                    defaultDate: new Date(),
                    timeFormat: 'h(:mm)a',
                    header: {
                        left: 'prev,next',
                        center: 'title',
                    },
                    eventLimit: true,
                    events: events,
                    selectable: true,
                    select: function(start, end, jsEvent, view) {
                        Swal.fire({
                            title: 'Заполните поля',
                            html:
                                '<form method="post">'+
                                '<div asp-validation-summary="ModelOnly"></div> <div>'+
                                '<label for="NameOfTour">Название турнира</label><br />'+
                                '<input id="NameOfTour" /></div>'+
                                '<div><label for="DateOfTournament"> Дата проведения</label><br />'+
                                '<input value="' +moment(start).format()+'" type="date" id="DateOfTournament"></div>'+
                                '<div><label for="UserCountOfTour">Количество участников</label><br />'+
                                '<input id="UserCountOfTour" /></div>'+
                                '<div> <label for="Category">Категория</label><br />'+
                                '<select id="Category">'+
                                '<option>Выберите категорию</option> <option value="0">Futures</option><option value="1">Masters</option>' +
                                '<option value="2">Promasters</option></select > </div > '+
                                '<div><label for="Type">Тип турнира</label><br />'+
                                '<select id="Type">'+
                                '<option>Выберите тип</option><option value="0">ManOne</option><option value="1">WomenOne</option>' +
                                '<option value="2">ManTwo</option><option value="3">WomenTwo</option><option value="4">Mixed</option></select></div>' +
                                '<div><label for="League">Лига турнира</label><br />'+
                                '<select id="League">'+
                                '<option>Выберите лигу</option><option value="0">Highest</option><option value="1">First</option>' +
                                '<option value="2">Second</option><option value="3">Third</option><option value="4">Fourth</option></select></div>' +
                                '<div><input type="submit" value="Добавить" data-dismiss="modal" class="mt-2 btn btn-primary" onclick="AddTournament()" /></div>'+
                                '</form>',
                            showCancelButton: true,
                            showConfirmButton: false
                        })
                    }
                })
            }
        })
        function AddTournament() {
            console.log("Nazvanie", $("#NameOfTour").val());
            console.log("Kol-vo", $("#UserCountOfTour").val());
            console.log("Data", $("#DateOfTournament").val());
            const categoria = $('#Category').find(":selected").text();
            console.log(categoria);
            console.log("Categoria", $("#Category").val());
            console.log("Tip", $("#Type").val());
            console.log("Liga", $("#League").val());
            let tour = {
                'Name': $("#NameOfTour").val(),
                'Date': $("#DateOfTournament").val(),
                'UserCount': $("#UserCountOfTour").val(),
                'Category': $("#Category").val(),
                'Type': $("#Type").val(),
                'CategoryLeagueTournament': $("#League").val(),
            }
            console.log(tour);
            $.ajax({
             url: '@Url.Action("Create","Tournament")',
             type: "POST",
             async: false,
             cache: false,
             data: tour,
                success: function (response) {
                    location.reload();
             }
            });
        }
    </script>
}