Models/Tournament.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Tennis.Models
{
    public enum CategoryTournament
    {
        Futures,
        Masters,
        Promasters
    }

    public enum CategoryLeagueTournament
    {
        Highest,
        First,
        Second,
        Third,
        Fourth
    }

    public enum Type
    {
        ManOne,
        WomenOne,
        ManTwo,
        WomenTwo,
        Mixed
    }

    public enum StatusTournament
    {
        Was,
        Will,
    }

    public enum TournamentScoreStatus
    {
        On,
        Off

    }
    public enum TournamentQueueStatus
    {
        MainStaff,
        Spare
    }

    public enum TournamentRate
    {
        Superior,
        First,
        Second,
        Third,
        Fourth
    }

    public class Tournament
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public DateTime Date { get; set; }
        public CategoryTournament Category { get; set; }
        public CategoryLeagueTournament CategoryLeagueTournament { get; set; }
        public Type Type { get; set; }
        [Required]
        public int UserCount { get; set; }
        public StatusTournament Status { get; set; }

    }
}

Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tennis.Models;
using Tennis.ViewModels;
namespace Tennis.Controllers
{
    public class TournamentController : Controller
    {
        private UsersContext _db;
        public TournamentController(UsersContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var tournamets = _db.Tournaments.OrderByDescending(x => x.Date).ToList();
            return View(tournamets);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<OkObjectResult> Create(Tournament tournament)
        {
            if (tournament != null)
            {
                if (tournament.Date > DateTime.Now)
                {
                    tournament.Status = StatusTournament.Will;
                }
                else
                {
                    tournament.Status = StatusTournament.Was;
                }
                await _db.Tournaments.AddAsync(tournament);
                await _db.SaveChangesAsync();
                return Ok(tournament);
            }
            return Ok("There are some troubles");
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public OkObjectResult ConfirmationOfClosing(List<string> playersId, List<int> postitions, string Id)
        {
            if (playersId != null && Id != null && postitions != null)
            {
                var _tournament = _db.Tournaments.FirstOrDefault(x => x.Id == Id);
                var tournamentScores = _db.userTournaments.Where(x => x.TournamentId == Id).OrderByDescending(x => x.Points).ToList();
                
                foreach (var item in tournamentScores)
                {
                    for (int i = 0; i < playersId.Count; i++)
                    {
                        if (item.UserId == playersId[i]) 
                        {
                            item.Place = postitions[i];
                            item.Tournament.Status = StatusTournament.Was;
                            _db.userTournaments.Update(item);
                            _db.SaveChanges();
                            
                        }
                        if (item.GuestId == playersId[i])
                        {
                            item.Place = postitions[i];
                            item.Tournament.Status = StatusTournament.Was;
                            _db.userTournaments.Update(item);
                            _db.SaveChanges();

                        }
                    }
                   
                }
                if (_tournament.Status != StatusTournament.Was)
                {
                    return Ok("Не получилось, попробуйте еще раз");

                }
                return Ok("ОК");
            }
            else
                return Ok("Не получилось, попробуйте еще раз");
        }

        [Authorize(Roles = "admin")]
        public IActionResult Close(string Id)
        {
            var tournament = _db.Tournaments.FirstOrDefault(x => x.Id == Id);
            if (tournament != null && tournament.Status != StatusTournament.Was)
            {
               var tournamentScores = _db.userTournaments.Where(x => x.TournamentId == Id).OrderByDescending(x => x.Points).ToList();
                foreach(var i in tournamentScores)
                {
                    if(i.UserId != null)
                        i.User = _db.Users.FirstOrDefault(u => u.Id == i.UserId);
                    else if(i.GuestId != null)
                        i.Guest = _db.Guests.FirstOrDefault(u => u.Id == i.GuestId);
                }
                TournamentScoreViewModel scoreViewModel = new TournamentScoreViewModel()
                {
                    tournament = tournament,
                    tournamentScores = tournamentScores
                };
               return View(scoreViewModel);
            }
            return View();
        }
        [Authorize(Roles = "admin")]
        public ActionResult CloseTournament(string id)
        {
            var tournament = _db.Tournaments.FirstOrDefault(t => t.Id == id);
            return View(tournament);
        }
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("CloseTournament")]
        public ActionResult CloseConfirmed(string id)
        {
            var tournament = _db.Tournaments.FirstOrDefault(t => t.Id == id);
            tournament.Status = StatusTournament.Was;
            _db.Tournaments.Update(tournament);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DetailsTournament(string Id)
        {
            var tournament = _db.Tournaments.FirstOrDefault(t => t.Id == Id);
           
            if (tournament != null)
            {
                var userTournament = _db.userTournaments.Where(u => u.TournamentId == Id && u.Status == StatusPlayers.In_Tour).ToList();
                ViewBag.TournamentRemainingSeats = tournament.UserCount - userTournament.Count;
                return View(tournament);
            }
            return NotFound("Турнир не найден!");
        }


        [HttpPost]
        [Authorize(Roles = "admin")]

        public IActionResult TournamentRemove(string Id)
        {
            var tournament = _db.Tournaments.FirstOrDefault(t => t.Id == Id);
            if(tournament != null)
            {
                var tournamentPlayers = _db.AllTournamentPlayers.Where(p => p.TournamentId == Id).ToList();
                var userTournament = _db.userTournaments.Where(u => u.TournamentId == Id).ToList();
                var pairPlayers = _db.PlayersPairs.Where(p => p.TournamentId == Id).ToList();
                if (tournamentPlayers.Count != 0)
                    tournamentPlayers.ForEach(t => _db.Remove(t));
                if (userTournament.Count != 0)
                    userTournament.ForEach(t => _db.Remove(t));
                if (pairPlayers.Count != 0)
                    pairPlayers.ForEach(t => _db.Remove(t));
                _db.Remove(tournament);
                _db.SaveChanges();
                return Ok();
            }
            return NotFound("Турнир не найден!");
        }
    }
}

Views/Tournament/Close.cshtml
@model Tennis.ViewModels.TournamentScoreViewModel


<div class="container">
    <div>


        @if (Model.tournamentScores != null)
        {
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col">Имя</th>
                        <th scope="col">Место</th>
                    </tr>
                </thead>
                <tbody id="users">
                    @foreach (var item in @Model.tournamentScores)
                    {
                        <tr>
                            @if (@item.User == null)
                            {

                                <td><input type="hidden" value="@item.GuestId" class="players_id" /></td>
                                <td class="mr-5" id="player_id">@item.Guest.Name</td>
                            }
                            else
                            {

                                <td><input type="hidden" value="@item.UserId" class="players_id" /></td>
                                <td class="mr-5" id="player_id">@item.User.Name</td>
                            }

                            <td class="mr-5">
                                <input id="userPosition" type="number" value="0" class="inputs" min="1" max="@item.Tournament.UserCount" />
                            </td>


                        </tr>
                    }
                </tbody>
            </table>
            @if (User.IsInRole("admin"))
            {
                @if (Model.tournament.Status == Tennis.Models.StatusTournament.Will)
                {
                    <div class="mt-3">
                        <button class="btn btn-primary" value="Закрыть" onclick="SaveData('@Model.tournament.Id')">Закрыть</button>
                    </div>
                    <p id="positionCheck"></p>
                }
            }
        }
        else
        {
            <p>Нет данных</p>
        }
    </div>
</div>
@section Scripts
    {
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <script>

        function SaveData(Id) {
            const tableBody = document.getElementById('users');
            const bodyTrs = tableBody.getElementsByTagName('tr');
            console.log(bodyTrs);
            var nums = [];
            var Ids = [];
            var playersId = document.getElementsByClassName('players_id');
            var inputs = document.getElementsByClassName('inputs');
            var positions = [];
            for (let i = 0; i < bodyTrs.length; i++) {
                nums[i] = bodyTrs[i].getElementsByTagName('td');
                Ids[i] = playersId[i].value
                positions[i] = inputs[i].value;
            }
            var txt = "";
            if (document.getElementById("userPosition").validity.rangeUnderflow) {
                txt = "Значения не могут быть меньше 1 или больше количества участников";
            } else if (document.getElementById("userPosition").validity.rangeOverflow) {
                txt = "Значения не могут быть меньше 1 или больше количества участников";
            } else {
                $.post('@Url.Action("ConfirmationOfClosing", "Tournament")',
            {
                playersId: Ids,
                postitions: positions,
            Id: Id,
        },
        function (response) {
        console.log(response)
            if (response === "ОК") {
                swal("Урааа!", "Вы успешно закрыли турнир и проставили места.", "success");
                setTimeout(function () {
                    window.location.href = 'https://localhost:44349/Tournament';
                }, 3000);
            } else {
                swal("Ой!", response, "info");
            }
            });
            }
            document.getElementById("positionCheck").innerHTML = txt;
        };

    </script>
}

Views/Tournament/CloseTournament.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }
@model Tournament
<div class="container">

<h2>Закрытие турнира без проставления мест</h2>
<dl>
    <dt>Название</dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
</dl>

@using (Html.BeginForm())
{
    <input type="submit" value="Подтвердить удаление" />
}
</div>

Views/Tournament/DetailsTournament.cshtml
@model Tournament
@{ ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml"; }
<div class="container">
    <div class="card text-center">
        <div class="card-header">
            <h3>@Model.Name</h3>
        </div>
        <div class="card-body">
            <h6 class="text-muted">Категория</h6>
            <h3 class="card-title">@Model.Category.ToString()</h3>
            @if (User.IsInRole("admin"))
            {
                <h6 class="text-muted">Статус</h6>
                <h3 class="card-title">@Model.Status.ToString()</h3>
            }
            <h6 class="text-muted">Лига турнира</h6>
            <h3 class="card-title">@Model.CategoryLeagueTournament.ToString()</h3>
            <h6 class="text-muted">Тип турнира</h6>
            <h3 class="card-title">@Model.Type.ToString()</h3>
            @if (Model.Status == StatusTournament.Will)
            {
                <h6 class="text-muted">Допустимое количество участников</h6>
                <h3 class="card-title text-success">@Model.UserCount.ToString()</h3>
                <h6 class="text-muted">Сколько мест осталось</h6>
                <h3 class="card-title text-success">@ViewBag.TournamentRemainingSeats</h3>
            }
            else
            {
                <h3 class="text-muted">Турнир уже окончен</h3>
            }

            @if (User.IsInRole("admin"))
            {
                @if (Model.Status == StatusTournament.Will)
                {
                    <a class="btn btn-danger" asp-action="CloseTournament" asp-controller="Tournament" asp-route-Id="@Model.Id">Закрыть турнир без проставления мест</a>
                    <a class="btn btn-danger" asp-action="Close" asp-controller="Tournament" asp-route-Id="@Model.Id">Закрыть турнир</a>
                    <a asp-controller="TournamentPlayer" asp-action="Application" asp-route-id="@Model.Id" class="text-light btn btn-danger" style="text-decoration: none">Заявки</a>
                    <a asp-controller="TournamentPlayer" asp-action="ApproveApplication" asp-route-id="@Model.Id" class="text-light btn btn-danger" style="text-decoration: none">Одобренные Заявки</a>
                    <a asp-controller="TournamentPlayer" asp-action="DeclinedApplication" asp-route-id="@Model.Id" class="text-light btn btn-danger" style="text-decoration: none">Отклонённые Заявки</a>
                }
                <a onclick="tournamentRemove('@Model.Id')" class="text-light btn btn-danger">Удалить</a>
            }
            @if (Model.Status != StatusTournament.Was)
            {
                string id_main_block = "main_" + Model.Id;
                string id_button = "button_" + Model.Id;
                string check_msg = "check_msg_" + Model.Id;
                if (User.IsInRole("user"))
                {
                    if (Model.Type == Tennis.Models.Type.ManOne || Model.Type == Tennis.Models.Type.WomenOne)
                    {
                        <div id="@check_msg"></div>
                        <div id="@id_main_block">
                            <button class="btn btn-success" id="@id_button" onclick="applyfunction('@Model.Id')">
                                Участвовать
                            </button>
                        </div>
                    }
                    else
                    {
                        <div id="@check_msg"></div>
                        <div id="@id_main_block">
                            <button type="button" onclick="openbuttons('@Model.Id')" class="btn btn-success" data-toggle="modal" data-target="#apllyGuest">
                                Участвовать
                            </button>
                        </div>
                    }
                }
                else if (!User.IsInRole("user") && !User.IsInRole("admin"))
                {
                    <div id="@check_msg"></div>
                    <div id="@id_button">
                        <button type="button" onclick="openbuttons('@Model.Id')" class="btn btn-success" data-toggle="modal" data-target="#apllyGuest">
                            Участвовать
                        </button>
                    </div>
                }
            }
        </div>
        <div class="card-footer">
            <h6 class="text-muted">Дата начало</h6>
            @Model.Date.ToString();
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(function() { update() });
        function applyfunction(id_t) {
            $.post('@Url.Action("Apply", "TournumentScore")', {
                tournament_Id: id_t,
            }, function (response) {
                update();
                console.log(response);
                if (response === "ОК") {
                    swal("Урааа!", "Ваша заявка принята. Ожидайте пока организатор одобрит", "success");
                } else {
                    swal("Ой!", response, "info");
                }
            })
        }

        function tournamentRemove(id) {
            swal({
                title: "Внимание!",
                text: "Вы уверены что хотите удалить турнир? После удаления турнира, все заявки на этот турнир также будут удалены.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        $.post('@Url.Action("TournamentRemove", "Tournament")', {
                            id,
                        }, function (response) {
                            swal("Турнир успешно удален!", {
                                icon: "success",
                            })
                            window.location.href = '@Url.Action("Index", "Tournament")';
                        });
                    } else {
                        swal("Удаление турнира отменена!");
                    }
                });
        }

        let update = function () {
            $.get('@Url.Action("GetTournamentUsers", "TournumentScore")',
                function (response) {
                    if (response != null) {
                        for (let i = 0; i < response.length; i++) {
                            if (response[i].status === 0) {
                                $('#check_msg_' + response[i].tournamentId).empty();
                                $('#main_' + response[i].tournamentId).empty();
                                $('#main_' + response[i].tournamentId).append('<p class="text-success">Ваша заявка одобрено. Теперь вы участник этого турнира</p>');
                            } else if (response[i].status === 1) {
                                $('#check_msg_' + response[i].tournamentId).empty();
                                $('#check_msg_' + response[i].tournamentId).append('<br/><p class="text-danger">Ваша заявка отклонена. </p>');
                            } else if (response[i].status === 2 || response[i].status === 3) {
                                $('#check_msg_' + response[i].tournamentId).empty();
                                $('#main_' + response[i].tournamentId).empty();
                                $('#main_' + response[i].tournamentId).append('<p class="text-secondary">Заявка на участие в турнире находится в обработке</p>');
                            }
                        }
                    }
                })
        }

        function submitPair() {
            let getId = $('#pairSub').attr('name');
            $.post('@Url.Action("Apply", "TournumentScore")', {
                tournament_Id: getId,
                pref: $('#pairPref_' + getId).val()
            }, function (response) {
                update();
                console.log(response);
                $('#closeButton').click();
                if (response === "ОК") {
                    swal("", "Ваша заявка принята. Ожидайте пока организатор одобрит", "success");
                } else {
                    swal("Oops!", response, "info");
                }
            })
        }

        function AddTournament() {
        let tour = {
            'Name': $("#Name").val(),
            'UserCount': $("#UserCount").val(),
            'Date': $("#DateOfTournament").val(),
            'Category': $("#Category").val(),
            'Type': $("#Type").val(),
            'CategoryLeagueTournament': $("#League").val(),
            }
            $.ajax({
             url: '@Url.Action("Create","Tournament")',
             type: "POST",
             async: false,
             cache: false,
             data: tour,
                success: function (response) {
                    location.reload();
             }
            });
        }

        //Заявка гостей

        var userAuthorized = @User.Identity.IsAuthenticated.ToString().ToLower();

        if (userAuthorized == true) {
            function openbuttons(id) {
                Swal.fire({
                    title: 'Здесь вы можете указать напарника для участия',
                    html: '<input type="text" id="pairPref_' + id + '"/><br/>' +
                        '<a class="btn btn-primary mb-1 mt-2 text-white" id="pairSub" type="submit" name="' + id + '" onclick="submitPair()">Подтвердить<a/>',
                    showCancelButton: true,
                    showConfirmButton: false
                })
            };
        }
        else {
            function openbuttons(id) {
                Swal.fire({
                    title: 'Выберите как участвовать',
                    html:
                        '<a class="btn btn-primary mb-1" href="/Account/Login">Принять участие как член КСЛТ</a><br/><a class="btn btn-primary mb-1" href="/Account/Register">' +
                        'Стать членом КСЛТ и принять участие</a><br/><a class="btn btn-primary" onclick="modalFormAplly()">Принять участие как гость</a><p id="getId" name="' + id + '"></p>',
                    showCancelButton: true,
                    showConfirmButton: false
                })
            };
        }

        function modalFormAplly() {
            let getId = $('#getId').attr('name');
            Swal.fire({
                title: 'Заполните поля',
                html:
                    '<form><div class="form-group">'
                + '<label for="name">Имя</label><br />'
                + '<p id="nameCheck" class="text-danger"></p>'
                + '<input class="form-control" id="name" placeholder="Имя" required />'
                + '</div>'
                + '<div class="form-group">'
                + '<label for="tel">Номер телефона</label><br />'
                + '<p id="telCheck" class="text-danger"></p>'
                + '<input class="form-control" type="number" id="tel" placeholder="Номер телефона" required>'
                + '</div>'
                + '<a class="btn btn-primary" onclick="functionPostData()">Отправить</a>'
                    + '<p id="postTournamentId" name="' + getId + '"></p></form>',
                showCancelButton: true,
                showConfirmButton: false
            })
        };

        function functionPostData() {
            if ($('#name').val().length != 0) {
                $('#nameCheck').empty();
                if ($('#tel').val().length == 12 || $('#tel').val().length == 10) {
                    $('#telCheck').empty();
                    var guest = {
                        'PhoneNumber': $('#tel').val(),
                        'Name': $('#name').val(),
                    };
                    let id = $('#postTournamentId').attr('name');
                    $.post('@Url.Action("ApplyGuest", "TournumentScore")', {
                        guest,id
                        },
                        function (response) {
                            $('#closeButton').click();
                            if (response === "ОК") {
                                swal("Урааа!", "Ваша заявка принята. Ожидайте пока организатор одобрит", "success");
                            } else {
                                swal("Ой!",response , "info");
                            }
                        })
                } else {
                    $('#telCheck').empty();
                    $('#telCheck').append('Длина номера должна быть 10 или 12 символов');
                }
            } else {
                $('#nameCheck').empty();
                $('#nameCheck').append('Укажите пожалуйста имя');
            }
        };
    </script>
}